### ISSUE TITLE
As the system, I can Categorize occupations

### ISSUE THREAD

**Issue by jpoulsenjr** [alphanexustech/role-directory-proto#4]
- [x] create role class
- [x] good work adding getter/setter for name, try getter/setter with other attributes: description, num_employed, mean_hourly_wage, etc.)
- [x] finish data structure for mapping (see below comment with 9 attributes below)
- [x] #13
- [x] #14

**Comment by nbuechler** [comment]
Role class possible attributes:

field_of_work: string[] (govt, trade, business, entertainment)
services_provided: string[]
level_of_income: string
essential: string (maybe?? essential, partially essential, non essential)

Other possible attributes from BLS:
Employment 
EmploymentRSE
Mean hourlywage
Mean annualwage 
Wage RSE

**Comment by nbuechler** [comment]
@jpoulsenjr - Here's the example data structure for the following attributes to add:

`(<category>, (<values,>), (<keys,>)`

So as an example, another program could use the setter with this data:

`('Employment Services', (572290, 16.41, 15.10, 31410), ('employment', 'percent_of_industry_employment', 'hourly_mean_wage', 'hourly_mean_wage', 'annual_mean_wage'))`

Important: Keep in mind, the amount of keys/columns, will vary between attributes, and we can create classes for them in the future to ensure data quality, but for this version the getters and setters below should be fine.

An example setter might look like this:

```
# x === <category>, y === (<values,>), z === (<keys,>)
def set_percentile_90(self, x, y, z):
        self.__percentile_90 = (x, y, z)
```

For the following attributes:

- [x] industry_highest_level_employment
- [x] industry_highest_concentration_employment
- [x] industry_top_paying_industries
- [x] state_highest_level_employment
- [x] state_highest_concentration_employment
- [x] state_top_paying
- [x] metropolitan_highest_level_employment
- [x] metropolitan_highest_concentration_employment
- [x] metropolitan_top_paying
- [x] non_metropolitan_highest_level_employment
- [x] non_metropolitan_highest_concentration_employment
- [x] non_metropolitan_top_paying

**Comment by nbuechler** [comment]
@jpoulsenjr - remember to click the tasks that are done, I took the other two an made them enhancements. Close the task when you are done.

**Comment by nbuechler** [comment]
Nevermind, you clicked on my computer, so I'll close this. Nice work!
